
-- Obsolete !!!
--
-- This query not need to be used instead in by EF6 using in DATA layer
--
-- see the Migarations folder in Portnox.Data class librarry
--

USE [master]
GO

/****** Object:  Database [PortnoxDb]    Script Date: 11/12/2019 6:58:42 PM ******/
CREATE DATABASE [PortnoxDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PortnoxDb', FILENAME = N'D:\Users\avd\PortnoxDb.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PortnoxDb_log', FILENAME = N'D:\Users\avd\PortnoxDb_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PortnoxDb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PortnoxDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PortnoxDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PortnoxDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PortnoxDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PortnoxDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PortnoxDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [PortnoxDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PortnoxDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PortnoxDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PortnoxDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PortnoxDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PortnoxDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PortnoxDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PortnoxDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PortnoxDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PortnoxDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PortnoxDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PortnoxDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PortnoxDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PortnoxDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PortnoxDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PortnoxDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PortnoxDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PortnoxDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PortnoxDb] SET  MULTI_USER 
GO

ALTER DATABASE [PortnoxDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PortnoxDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PortnoxDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PortnoxDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PortnoxDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PortnoxDb] SET  READ_WRITE 
GO


